name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build 
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'
    - name: Install dependencies
      run: npm install
    - name: Lint Check
      run: npm run lint
    - name: Run Unit Tests
      run: npm test
    test:
      runs-on: ubuntu-latest
      needs: lint
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'
      - name: Install dependencies
        run: npm install
      - name: Lint Check
        run: npm run lint
      - name: Run Unit Tests
        run: npm test
