# Name of the workflow
name: Node.js CI

# Events that trigger the workflow
on:
  push:
    branches: [main]       # Trigger on push to 'main' branch
  pull_request:
    branches: [main]       # Trigger on pull requests to 'main' branch

# Define the jobs to be run as part of this workflow
jobs:
  # Job for building the project
  build:
    runs-on: ubuntu-latest # Specifies the runner environment
    steps:
      - uses: actions/checkout@v2               # Checks out the repository code
      - name: Use Node.js
        uses: actions/setup-node@v2             # Sets up Node.js environment
        with:
          node-version: "20.11.0"                # Specify Node.js version to use

      # Cache Node.js modules to speed up builds
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm                          # Directory to cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  # Cache key
          restore-keys: |                       # Fallback keys
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install                         # Installs project dependencies
      - name: Build
        run: npm run build                       # Builds the project

  # Job for linting (finds erros and stuff) the code
  lint:
    runs-on: ubuntu-latest
    needs: build                                # Depends on successful build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"
      - name: Install dependencies
        run: npm install
      - name: Lint Check
        run: npm run lint                        # Runs linting on the codebase
      - name: Run Unit Tests
        run: npm test                            # Runs unit tests

  # Job for running unit tests
  test:
    runs-on: ubuntu-latest
    needs: lint                                 # Depends on successful lint
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"

      # Cache Node.js modules to speed up unit testing
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
      - name: Lint Check
        run: npm run lint                        # Ensures linting before testing
      - name: Run Unit Tests
        run: npm test                            # Executes unit tests
